// API Configuration
// This file is generated by start_frontend.ps1 from .env settings
// Do not edit directly if you are using the start script

window.API_CONFIG = {
    baseURL: 'http://localhost:8001/api',
    timeout: 30000
};
