# Start Frontend Script
# This script reads .env, updates js/config.js, and starts the Python HTTP server

$ErrorActionPreference = "Stop"

Write-Host "[START] Starting Cybersecurity Club Frontend..." -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Gray

# 1. Read .env file
$envPath = Join-Path $PSScriptRoot ".env"
$configPath = Join-Path $PSScriptRoot "js/config.js"

if (Test-Path $envPath) {
    Write-Host "[INFO] Reading configuration from .env..." -ForegroundColor Yellow
    # Force UTF8 reading to handle potentially BOM-less UTF8 from Node/Python tools
    $envContent = Get-Content $envPath -Encoding UTF8
    $config = @{}
    
    foreach ($line in $envContent) {
        if ($line -match "^([^#=]+)=(.*)$") {
            $key = $matches[1].Trim()
            $value = $matches[2].Trim()
            $config[$key] = $value
            Write-Host "   Loaded: $key = $value" -ForegroundColor Gray
        }
    }
} else {
    Write-Host "[WARN] .env file not found. Using defaults." -ForegroundColor Yellow
    $config = @{
        "API_BASE_URL" = "http://localhost:8001/api"
        "API_TIMEOUT" = "30000"
        "FRONTEND_PORT" = "5500"
    }
}

# Ensure defaults if keys missing
if (-not $config.ContainsKey("API_BASE_URL")) { $config["API_BASE_URL"] = "http://localhost:8001/api" }
if (-not $config.ContainsKey("API_TIMEOUT")) { $config["API_TIMEOUT"] = "30000" }
if (-not $config.ContainsKey("FRONTEND_PORT")) { $config["FRONTEND_PORT"] = "5500" }

# 2. Update js/config.js configuration
Write-Host "[INFO] Updating js/config.js..." -ForegroundColor Yellow

$jsConfigContent = @"
// API Configuration
// This file is generated by start_frontend.ps1 from .env settings
// Do not edit directly if you are using the start script

window.API_CONFIG = {
    baseURL: '$($config["API_BASE_URL"])',
    timeout: $($config["API_TIMEOUT"])
};
"@

Set-Content -Path $configPath -Value $jsConfigContent
Write-Host "[OK] Configuration updated" -ForegroundColor Green

# 3. Kill existing python http server on the port (if any)
$webPort = $config["FRONTEND_PORT"]
Write-Host "[INFO] Checking port $webPort..." -ForegroundColor Yellow

# Rough way to kill python process on Windows (might kill others, but usually safe in this context)
$tcpConnections = Get-NetTCPConnection -LocalPort $webPort -ErrorAction SilentlyContinue

if ($tcpConnections) {
    Write-Host "[WARN] Port $webPort is in use. Attempting to clear..." -ForegroundColor Yellow
    Stop-Process -Name "python" -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
}

# 4. Start Server
Write-Host "[INFO] Starting HTTP Server on port $webPort..." -ForegroundColor Green
Write-Host "   Open browser to: http://localhost:$webPort" -ForegroundColor Cyan

Start-Process python -ArgumentList "-m http.server $webPort" -WorkingDirectory $PSScriptRoot -WindowStyle Minimized

Write-Host "[OK] Server started (Minimized window)" -ForegroundColor Green
