"""Add feedback table

Revision ID: 05584eb6f18d
Revises: b9e4f5a2c3d1
Create Date: 2026-03-11 20:27:49.132698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05584eb6f18d'
down_revision = 'b9e4f5a2c3d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year_class_roll', sa.String(length=100), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('practical_concepts_rating', sa.Integer(), nullable=False),
    sa.Column('interesting_rating', sa.String(length=50), nullable=False),
    sa.Column('difficulty_rating', sa.String(length=50), nullable=False),
    sa.Column('enjoyed_category', sa.String(length=50), nullable=False),
    sa.Column('improved_skills', sa.String(length=20), nullable=False),
    sa.Column('encouraged_teamwork', sa.String(length=20), nullable=False),
    sa.Column('valuable_learning', sa.Text(), nullable=False),
    sa.Column('challenges_faced', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('liked_challenges', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_email'), 'feedback', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_email'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
