"""Split feedback year class roll field

Revision ID: b89303a00fc4
Revises: 05584eb6f18d
Create Date: 2026-03-11 20:51:18.807776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89303a00fc4'
down_revision = '05584eb6f18d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=20), nullable=False, server_default='N/A'))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=False, server_default='N/A'))
        batch_op.add_column(sa.Column('moodle_id', sa.String(length=20), nullable=False, server_default='N/A'))
        batch_op.drop_column('year_class_roll')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_class_roll', sa.VARCHAR(length=100), nullable=False, server_default='N/A'))
        batch_op.drop_column('moodle_id')
        batch_op.drop_column('department')
        batch_op.drop_column('year')
    # ### end Alembic commands ###
